In [57]:
text=[]
with open('/kaggle/input/new-data/data.txt','r',encoding='utf-8') as f:
    while(f.readline()):
        text.append(f.readline())

In [58]:
text

['Thank you for your prompt response\n',
 'Please find attached the document you requested\n',
 'Your attention to detail is truly commendable\n',
 'It was a pleasure meeting you at the conference\n',
 'I wanted to express my gratitude for your support\n',
 'Your insights have been instrumental in our decision-making process\n',
 'Please let me know if you require any further clarification\n',
 'I am thrilled to be a part of this exciting initiative\n',
 'The attached report contains a comprehensive analysis\n',
 'I apologize for any inconvenience caused\n',
 'Please be advised that there is a change in schedule\n',
 "Let's explore potential solutions to address this issue\n",
 'I am writing to request your assistance on a matter of importance\n',
 'I am confident that together we can overcome this challenge\n',
 'Your commitment to excellence is evident in your work\n',
 'The team has achieved remarkable progress in recent weeks\n',
 'Please find below a summary of our recent accompli

In [59]:
input_text=[]
for i in range(0,len(text),2):
    txt=''
    txt=txt + text[i].replace('\t',' ').replace('\n','')
    input_text.append(txt)

In [60]:
input_text

['Thank you for your prompt response',
 'Your attention to detail is truly commendable',
 'I wanted to express my gratitude for your support',
 'Please let me know if you require any further clarification',
 'The attached report contains a comprehensive analysis',
 'Please be advised that there is a change in schedule',
 'I am writing to request your assistance on a matter of importance',
 'Your commitment to excellence is evident in your work',
 'Please find below a summary of our recent accomplishments',
 'Your leadership has been a driving force behind our success',
 'The enclosed document provides a detailed overview of the proposal',
 'I wanted to acknowledge your outstanding performance',
 'Your dedication and hard work have not gone unnoticed',
 'Your commitment to meeting deadlines is truly appreciated',
 'Your creativity in problem-solving is an asset to the team',
 'Please find attached the agenda for our upcoming meeting',
 'It was a pleasure collaborating with you on this p

In [61]:
#Removing special characters
def full_stop(text):
  return text.replace(".","").replace("?","").lower()

In [62]:
new_input=[]
for i in input_text:
    new_input.append(full_stop(i))

In [64]:
new_input[9]

'your leadership has been a driving force behind our success'

In [65]:
import tensorflow as tf
import keras
from tensorflow.keras.preprocessing.text import Tokenizer


In [66]:
tokenizer=Tokenizer()

In [67]:
tokenizer.fit_on_texts(new_input)

In [68]:
tokenizer.word_index

{'to': 1,
 'the': 2,
 'a': 3,
 'i': 4,
 'you': 5,
 'for': 6,
 'your': 7,
 'in': 8,
 'and': 9,
 'of': 10,
 'on': 11,
 'is': 12,
 'have': 13,
 'project': 14,
 'our': 15,
 'team': 16,
 'it': 17,
 'with': 18,
 'would': 19,
 'should': 20,
 'can': 21,
 'may': 22,
 'my': 23,
 'new': 24,
 'that': 25,
 'work': 26,
 'we': 27,
 'industry': 28,
 'opportunities': 29,
 'will': 30,
 'am': 31,
 'could': 32,
 'are': 33,
 'culture': 34,
 "i'm": 35,
 'plan': 36,
 'time': 37,
 'challenges': 38,
 'professional': 39,
 'positive': 40,
 'any': 41,
 'about': 42,
 'need': 43,
 'please': 44,
 "let's": 45,
 'collaboration': 46,
 'might': 47,
 'explore': 48,
 'initiatives': 49,
 'enhance': 50,
 'development': 51,
 'workplace': 52,
 'actively': 53,
 'be': 54,
 'within': 55,
 'an': 56,
 'address': 57,
 'out': 58,
 'changes': 59,
 'must': 60,
 'recent': 61,
 'like': 62,
 'me': 63,
 'feedback': 64,
 'strategies': 65,
 'training': 66,
 "company's": 67,
 'success': 68,
 'market': 69,
 'crucial': 70,
 'continuous': 71,
 

In [69]:
number_of_words=len(tokenizer.word_index)-1

In [70]:
number_of_words

1751

In [71]:
input_sequences = []
for sentence in input_text:
  tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]

  for i in range(1,len(tokenized_sentence)):
    input_sequences.append(tokenized_sentence[:i+1])

In [72]:
input_sequences

[[120, 5],
 [120, 5, 6],
 [120, 5, 6, 7],
 [120, 5, 6, 7, 398],
 [120, 5, 6, 7, 398, 709],
 [7, 136],
 [7, 136, 1],
 [7, 136, 1, 217],
 [7, 136, 1, 217, 12],
 [7, 136, 1, 217, 12, 179],
 [7, 136, 1, 217, 12, 179, 218],
 [4, 121],
 [4, 121, 1],
 [4, 121, 1, 149],
 [4, 121, 1, 149, 23],
 [4, 121, 1, 149, 23, 161],
 [4, 121, 1, 149, 23, 161, 6],
 [4, 121, 1, 149, 23, 161, 6, 7],
 [4, 121, 1, 149, 23, 161, 6, 7, 73],
 [44, 180],
 [44, 180, 63],
 [44, 180, 63, 181],
 [44, 180, 63, 181, 97],
 [44, 180, 63, 181, 97, 5],
 [44, 180, 63, 181, 97, 5, 356],
 [44, 180, 63, 181, 97, 5, 356, 41],
 [44, 180, 63, 181, 97, 5, 356, 41, 464],
 [44, 180, 63, 181, 97, 5, 356, 41, 464, 972],
 [2, 278],
 [2, 278, 279],
 [2, 278, 279, 973],
 [2, 278, 279, 973, 3],
 [2, 278, 279, 973, 3, 219],
 [2, 278, 279, 973, 3, 219, 243],
 [44, 54],
 [44, 54, 974],
 [44, 54, 974, 25],
 [44, 54, 974, 25, 244],
 [44, 54, 974, 25, 244, 12],
 [44, 54, 974, 25, 244, 12, 3],
 [44, 54, 974, 25, 244, 12, 3, 280],
 [44, 54, 974, 25

In [73]:
max_len=max([len(x) for x in input_sequences])

In [74]:
max_len

19

In [75]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [76]:
padded_input_sequences=pad_sequences(input_sequences,maxlen=max_len,padding='pre')

In [77]:
padded_input_sequences

array([[  0,   0,   0, ...,   0, 120,   5],
       [  0,   0,   0, ..., 120,   5,   6],
       [  0,   0,   0, ...,   5,   6,   7],
       ...,
       [  0,   0,   0, ...,   7,  61, 265],
       [  0,   0,   0, ...,  61, 265,  33],
       [  0,   0,   0, ..., 265,  33, 483]], dtype=int32)

In [78]:
X=padded_input_sequences[:,:-1]

In [79]:
X

array([[  0,   0,   0, ...,   0,   0, 120],
       [  0,   0,   0, ...,   0, 120,   5],
       [  0,   0,   0, ..., 120,   5,   6],
       ...,
       [  0,   0,   0, ...,   0,   7,  61],
       [  0,   0,   0, ...,   7,  61, 265],
       [  0,   0,   0, ...,  61, 265,  33]], dtype=int32)

In [80]:
y=padded_input_sequences[:,-1]

In [81]:
y

array([  5,   6,   7, ..., 265,  33, 483], dtype=int32)

In [82]:
X.shape

(11485, 18)

In [83]:
y.shape

(11485,)

In [84]:
from keras.utils import to_categorical
y=to_categorical(y)

In [85]:
y.shape

(11485, 1753)

In [106]:
from keras import Sequential
from keras.layers import Embedding,Dense,SimpleRNN,LSTM

In [108]:
model =Sequential()
model.add(Embedding(number_of_words,300,input_shape=(18,)))
model.add(LSTM(150))
model.add(Dense(1753,activation='softmax'))

In [109]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [110]:
model.summary()

Model: "sequential_12"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_12 (Embedding)        │ (None, 18, 300)        │       525,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_4 (SimpleRNN)        │ (None, 150)            │        67,650 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1753)           │       264,703 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 857,653 (3.27 MB)

 Trainable params: 857,653 (3.27 MB)

 Non-trainable params: 0 (0.00 B)

In [111]:
history=model.fit(X,y,epochs=50)

Epoch 1/50
 31/359 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.0213 - loss: 7.1901

W0000 00:00:1713100431.674200      86 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update


359/359 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.0458 - loss: 6.5610
Epoch 2/50
 43/359 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.1217 - loss: 5.3812

W0000 00:00:1713100434.428891      86 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update


359/359 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.1528 - loss: 5.0655
Epoch 3/50
359/359 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.2875 - loss: 3.9080
Epoch 4/50
359/359 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.3971 - loss: 3.0936
Epoch 5/50
359/359 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.4756 - loss: 2.4952
Epoch 6/50
359/359 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.5664 - loss: 2.0028
Epoch 7/50
359/359 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.6284 - loss: 1.6707
Epoch 8/50
359/359 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.6803 - loss: 1.3669
Epoch 9/50
359/359 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7239 - loss: 1.1411
Epoch 10/50
359/359 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7543 - loss: 0.9843
Epoch 11/50
359/359 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7716 - loss: 0.8695
Epoch 12/50
359/359 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7875 - loss: 0.7847
Epoch 13/50
359/359 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accurac

In [116]:
import time
import numpy as np
text = "The movie was"

for i in range(20):
  # tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]
  # padding
  padded_token_text = pad_sequences([token_text], maxlen=max_len, padding='pre')
  # predict
  pos = np.argmax(model.predict(padded_token_text))

  for word,index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print()
      print(text)
      
      time.sleep(1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 443ms/step

The movie was a
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step

The movie was a healthy
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step

The movie was a healthy work
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step

The movie was a healthy work life
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step

The movie was a healthy work life balance
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step

The movie was a healthy work life balance care
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step

The movie was a healthy work life balance care to
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step

The movie was a healthy work life balance care to be
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step

The movie was a healthy work life balance care to be associated
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step

The movie was a healthy work life balance care to be associated with
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step

The movie was a healthy work life balance care to be associated with a
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step

The movie was a healthy work lif